### ISSUE TITLE
The first element is never deleted from the list

### ISSUE THREAD

**Issue by gallir** [cornelk/hashmap#10]
If you delete all the elements from the map, the first one in the list is never deleted.

If you add 
	for item := range m.Iter() {
		t.Errorf("map should be empty but got %v in the iterator.", item)
	}

to TestDelete() (shown below) you will see the error.

func TestDelete(t *testing.T) {
	m := &HashMap{}
	m.Del(0)

	elephant := &Animal{"elephant"}
	monkey := &Animal{"monkey"}
	m.Set(1, unsafe.Pointer(elephant))
	m.Set(2, unsafe.Pointer(monkey))
	m.Del(0)
	m.Del(3)
	if m.Len() != 2 {
		t.Error("map should contain exactly two elements.")
	}

	m.Del(1)
	m.Del(1)
	m.Del(2)
	if m.Len() != 0 {
		t.Error("map should be empty.")
	}

	for item := range m.Iter() {
		t.Errorf("map should be empty but got %v in the iterator.", item)
	}

	val, ok := m.Get(1) // Get a missing element.
	if ok {
		t.Error("ok should be false when item is missing from map.")
	}
	if val != nil {
		t.Error("Missing values should return as nil.")
	}

	m.Set(1, unsafe.Pointer(elephant))
}

**Comment by cornelk** [comment]
Thanks for reporting the bug, I could reproduce it and will look into it.

**Comment by smerkousdavid** [comment]
I'm running into the exact same problem. I was testing out my endpoints and when trying to delete the first endpoint it will not delete. However, if I delete the second element, then the first one disappears too until I create another element and the first (original) element reappears.

Example:
```
//Compile all of the regions
buff := bytes.NewBufferString("[")
if regions.Len() > 0 {
	logger.Log("SIZE %d", regions.Len())
	for r := range regions.Iter() {
		buff.WriteString(tJson(*(*crypto.Region)(r.Value)))
		buff.WriteString(",")
	}
	buff.Truncate(buff.Len() - 1)
}
buff.WriteString("]")
```
and
```
//Create the new region struct with the verified identity
region := &crypto.Region{
	Name: regionID,
	Ip: getPubIp(),
	Users: 1,
	Conn: conn,
	PublicKey: pubKey.(*rsa.PublicKey),
	PrivateKey: keyPair,
}

//Add the region to the global scope
regions.Set(regionID, unsafe.Pointer(region))
```

1) Adding the first returns:
[{"name":"d463943e-d78c-4605-a83b-206d5fbdc458","ip":"----","users":0}]

2) Deleting the first returns:
[]

3) Adding the new region (after deleting the first) returns:
[{"name":"3ebb3f5d-5811-4122-ac5b-3ad9837c58ff","ip":"----","users":0},
{"name":"d463943e-d78c-4605-a83b-206d5fbdc458","ip":"----","users":0}]

As you can see, the original value is still in the hashmap. Any ideas?

**Comment by cornelk** [comment]
This bug has been fixed in latest version.
