### ISSUE TITLE
ထ

### ISSUE THREAD

**Issue by OEmilius** [cornelk/hashmap#20]
Hello. 

 "github.com/cornelk/hashmap"
)

func main() {
 m := &hashmap.HashMap{}
 t0 := time.Now()
 for i := 1; i < 1000000; i++ {
  m.Set(i, "abc")
 }
 fmt.Println(time.Now().Sub(t0))

infinity wait time

sync.Map nearly 1.1080342s 
thank you

**Comment by MarcMagnin** [comment]
The project says "optimized for fastest read access".
Not sure about the write tho :)

**Comment by cornelk** [comment]
Running this test `go test -run TestBigMap -v` will show you that the writes are done but slow, but as documented this hashmap is not optimized (yet) for write performance.

```
func TestBigMap(t *testing.T) {
	m := New(1000000)
	t0 := time.Now()
	for i := 1; i < 1000000; i++ {
		m.Set(i, "abc")
		if i % 1000 == 0 {
			fmt.Println(i)
		}
	}
	fmt.Println(time.Now().Sub(t0))
}
```
