### ISSUE TITLE
Possible concurrency problem in `grow`

### ISSUE THREAD

**Issue by huandu** [cornelk/hashmap#21]
https://github.com/cornelk/hashmap/blob/master/hashmap.go#L329-L333

```go
func (m *HashMap) grow(newSize uintptr, loop bool) {
    // ...

    m.fillIndexItems(newdata) // initialize new index slice with longer keys

    atomic.StorePointer(&m.datamap, unsafe.Pointer(newdata))

    m.fillIndexItems(newdata) // make sure that the new index is up to date with the current state of the linked list

    // ...
}
```

If there is any data added while `grow` is running at first `m.fillIndexItems(newdata)`, such data may not be visible when `newdata` is set to `m.datamap` and second `m.fillIndexItems(newdata)` isn't done.

**Comment by skaldesh** [comment]
@cornelk Opinion?

**Comment by cornelk** [comment]
@huandu that is correct, however I would consider that situation as a write-delay, since the write operation will be done but the item only show up on Get requests after the second `fillIndexItems` is done.

**Comment by cornelk** [comment]
This behaviour is already documented: `https://godoc.org/github.com/cornelk/hashmap#HashMap.Set` 

`If a resizing operation is happening concurrently while calling Set, the item might show up in the map only after the resize operation is finished.`
