### ISSUE TITLE
List.Delete stucks in infinite loop

### ISSUE THREAD

**Issue by zhangcunli** [cornelk/hashmap#22]
List.Delete stucks in infinite loop:
The following is my test case:

package main
import (
	"github.com/cornelk/hashmap"
)
func main() {
	num := 128
	map1 := hashmap.New(uintptr(num))
	map1.Set("aa1", true)
	map1.Set("aa2", true)
	map1.Del("aa1")
}

//////////////////////////////////////////////////////////
1. But if I delete aa2 it work fine.
  	map1.Set("aa1", true)
	map1.Set("aa2", true)
	map1.Del("aa2")

//////////////////////////////////////////////////////////
2. And the following is also work fine.
  	map1.Set("a1", true)
	map1.Set("a2", true)
	map1.Del("a2")

**Comment by misha-plus** [comment]
I have this problem too. Maybe this is due instability of master branch. Maybe SemVer through tags will solve the problem?

**Comment by zhangcunli** [comment]
@misha-plus  https://github.com/cornelk/hashmap/pull/23   I have fix this issue.

**Comment by skaldesh** [comment]
Pull request is merged, please close this issue! @zhangcunli or @cornelk
