### ISSUE TITLE
About previousElement

### ISSUE THREAD

**Issue by XingzeGao** [cornelk/hashmap#26]
I just noticed that previousElement is not necessary for both set and get keys. Why do you still keep it?

**Comment by XingzeGao** [comment]
There is a potential problem that if I have two keys with same getHashKey value.
I modified getHashKey function and try to let it return same value all the time.
```
func TestHash(t *testing.T) {
	hash := hashmap.New(8)
	hash.Set("a" ,1)
	hash.Set("a" ,3)
	hash.Set("b" ,2)

	t.Log(hash.Get("a"))
	t.Log(hash.Get("b"))

}
```
The result of this test case is: a 2, nil false.

**Comment by cornelk** [comment]
`previousElement` is related to work in which I tried to improve the write performance.

**Comment by cornelk** [comment]
your test prints now:

```
    3 true
    2 true
```
