### ISSUE TITLE
I think that we should add extra handles in Delete call.

### ISSUE THREAD

**Issue by Nonnnnnnnnn** [cornelk/hashmap#28]
For example,List has items as {header,item1,item2,item3}.
When I want to delete item2 and item3  from List by asynchronous goroutines,as below.

[G2 ]  go Delete(item2) 
[G3 ]  go Delete(item3)

If G2 got runtime and deleted item2 first,and then G3 executed CAS to delete item3.
The item3's left was item2 before G3 executed CAS .
While item2's next was not be nil,in which case the CAS in G3 will not return false but go on.
In this case,item2's next was be set to item3's next,but the right result should be that item1's next is item3's next.

I think the next of item should be set to nil every Delete.

**Comment by cornelk** [comment]
Thanks for your bug report, indeed the old implementation had some issues, the current dev branch has a singly linked list which should not have those issues anymore. Please review and create a new ticket if you see any other issue, thanks!
