### ISSUE TITLE
How about use as counter map ？

### ISSUE THREAD

**Issue by Zeymo** [cornelk/hashmap#3]
I use a map for recording api invoke count in high conccurrency QPS which key is api , value is uint64，what's the efficient way to use this hashmap to implements 'increase value  atomiclly as `value++`' which actually don't need change unsafe.Pointer ?

**Comment by cornelk** [comment]
I added this good example of a use case as a test now: https://github.com/cornelk/hashmap/blob/master/hashmap_test.go#L250

**Comment by Zeymo** [comment]
cool, thanks!

**Comment by Zeymo** [comment]
when i use this map in production env, this occur a high cpu behavier amlost 100%, info is below

It will always has a gorutine in `grow`
``` 1: 16777216 [1: 16777216] @ 0x66f038 0x66eba2 0x66e5e2 0x50e79b 0x5035d6 0x4fe1a7 0x4ff907 0x4fd1e2 0x4f57c3 0x4f532e 0x4fa1ae 0x4608e1
#	0x66f037	mwcs/framework/datastructures/maps.(*HashMap).grow+0x67			/src/src/mwcs/framework/datastructures/maps/hashmap.go:266
#	0x66eba1	mwcs/framework/datastructures/maps.(*HashMap).insertListElement+0x131	/src/src/mwcs/framework/datastructures/maps/hashmap.go:190
#	0x66e5e1	mwcs/framework/datastructures/maps.(*HashMap).Insert+0xd1		/src/src/mwcs/framework/datastructures/maps/hashmap.go:121
```
hashmap.go:190 mapping
https://github.com/cornelk/hashmap/blob/master/hashmap.go#L174

hashmap.go:266 mapping
https://github.com/cornelk/hashmap/blob/master/hashmap.go#L255

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                            99.87s   100% |   mwcs/framework/datastructures/maps.(*List).Add
    92.89s 91.32% 91.32%     99.87s 98.18%                | mwcs/framework/datastructures/maps.(*List).search
                                             6.98s   100% |   mwcs/framework/datastructures/maps.(*ListElement).Next
----------------------------------------------------------+-------------
```

```
flat  flat%   sum%        cum   cum%
    92.89s 91.32% 91.32%     99.87s 98.18%  mwcs/framework/datastructures/maps.(*List).search
```

**Comment by cornelk** [comment]
This hashmap is optimized for fast reads, writes are currently not really optimized. To speed it up you should initialize the map with a larger size or even better initialize all keys with counter 0 on startup.

**Comment by Zeymo** [comment]
yeah，I initialize size as 1024 already . Info above since element too much and use up cpu ? or t there is competition ( maybe lock occupy?)  hidden danger

**Comment by cornelk** [comment]
can you initialize the hashmap with all keys with counter 0 on startup? please create a test so that i can replicate the behavior.

**Comment by Zeymo** [comment]
close it , if have further questions I will reopen it ：）

**Comment by cornelk** [comment]
I added a new GetOrInsert function for this usecase.

**Comment by Zeymo** [comment]
cool！
