### ISSUE TITLE
Benchmark failed

### ISSUE THREAD

**Issue by redseabay** [cornelk/hashmap#35]
I add log line before b.fai
					b.Logf("%s: error when i==%d", funcName, i)

and i noticed most i is 742, some is 178

if i change benchmarkItemCount to  512 (1<<9), i change to 385 390 403... seems it is not very random

CPU: amd ryzen 2600, ram 16G, os windows 7 64bit

BTW: race detect has no problem

my first log with an error log line:

    benchmark_test.go:88: BenchmarkReadHashMapUint: error when i:742 j: %!d(<nil>)
goos: windows
goarch: amd64
pkg: github.com/cornelk/hashmap
--- FAIL: BenchmarkReadHashMapWithWritesUint-12
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:178 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:742 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:178 j:%!d(<nil>)
    benchmark_test.go:114: BenchmarkReadHashMapWithWritesUint: error when i:178 j:%!d(<nil>)

benchmarkItemCount  changed to  512
--- FAIL: BenchmarkReadHashMapUint-12
    benchmark_test.go:109: BenchmarkReadHashMapUint: error when i==390
    benchmark_test.go:109: BenchmarkReadHashMapUint: error when i==390
    benchmark_test.go:109: BenchmarkReadHashMapUint: error when i==390
    benchmark_test.go:109: BenchmarkReadHashMapUint: error when i==390
    benchmark_test.go:109: BenchmarkReadHashMapUint: error when i==390

**Comment by cornelk** [comment]
I am not able to reproduce this.
