### ISSUE TITLE
Alignment on 32-bit platforms

### ISSUE THREAD

**Issue by edhemphill** [cornelk/hashmap#4]
While this project specifically calls out 64-bit platforms, I have a need to run it on 32-bit ARM as well.

I believe the sync.atomic functions will fail on 32-bit platforms if not properly aligned. This is noted in the bugs section at the bottom of this page.
https://golang.org/pkg/sync/atomic/#AddUint64

and there is an in-depth discussion here:
https://groups.google.com/forum/m/#!topic/golang-nuts/_nHK6P8_lhw

I think I can fix this. However, I just wanted to know if this is an issue you are already handling - or you even care about handling (totally makes since if its not).

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1a40e0]

goroutine 1 [running]:
panic(0x414338, 0x96f5e008)
	/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/panic.go:500 +0x33c
sync/atomic.addUint64(0x96ff5484, 0x1, 0x0, 0x1, 0x0)
	/usr/lib/arm-poky-linux-gnueabi/go/src/sync/atomic/64bit_arm.go:31 +0x68
github.com/WigWagCo/maestro/vendor/github.com/cornelk/hashmap.(*List).insertAt(0x96ff5480, 0x97012b40, 0x0, 0x0, 0x0)
	/builds/walt/42/wwrelay-rootfs/yocto/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/maestro/1.0+gitAUTOINC+dc7ed7782e-r0/go-workspace/src/github.com/WigWagCo/maestro/vendor/github.com/cornelk/hashmap/list.go:129 +0xa0
github.com/WigWagCo/maestro/vendor/github.com/cornelk/hashmap.(*List).AddOrUpdate(0x96ff5480, 0x97012b40, 0x970127e0, 0x97012820)```

**Comment by edhemphill** [comment]
See https://github.com/cornelk/hashmap/pull/5

**Comment by cornelk** [comment]
I am not working on 32 bit support , your contribution is welcome.

**Comment by cornelk** [comment]
32 bit support added.
