### ISSUE TITLE
Is Is Slow When Convert File To HashMap

### ISSUE THREAD

**Issue by qq408228727** [cornelk/hashmap#42]
//t.DataMap = &hashmap.HashMap{}
// Insert or Set cost long time when i read records from File To Hashmap when may app start
for _, item := range Records {
		//t.DataMap.Set(item.K, item)
		t.DataMap.Insert(item.K, item)

	}
// i use pprof show than List.search  cost most time
//by command:go tool pprof http://localhost:6060/debug/pprof/profile 
// github.com/cornelk/hashmap.(*List).search (29.72s)
//list.go(line:49) left, found, right := l.search(searchStart, element)
//so how can i avoid search  when my app start?

**Comment by qq408228727** [comment]
Is is Posible To  serialize deserialize the list  and hashmap? so i can use serialize  save to File and   deserialize read from file, and not searc anymore

**Comment by qq408228727** [comment]
Is is Posible To serialize deserialize the list and hashmap? so i can use serialize save to File and deserialize read from file, and not search anymore

**Comment by qq408228727** [comment]
Is it Posible To serialize deserialize the list and hashmap? so i can use serialize save to File and deserialize read from file, and not searc anymore

**Comment by qq408228727** [comment]
Is it Posible To serialize deserialize the list and hashmap? so i can use serialize save to File and deserialize read from file, and not search anymore

**Comment by cornelk** [comment]
closed in favor of duplicate #50
