### ISSUE TITLE
.Get on absent key fatalpanics

### ISSUE THREAD

**Issue by NikolayUvarov** [cornelk/hashmap#49]
When using next code got constantly fatalpanic. Probably it is because I'll try to get value from unexistent hash.
var val int
hKey:="new str"
actual, ok := hashTypeSubtype.Get(hKey)
val = actual.(int)
if !ok {
     val = 0
}
val++
hashTypeSubtype.Set(hKey, val)

**Comment by cornelk** [comment]
if the returned bool flag is false the value can not be used as the item does not exist.
