### ISSUE TITLE
Getting this error when there are many go routines trying to access the value

### ISSUE THREAD

**Issue by sudeepigntion** [cornelk/hashmap#55]
unexpected fault address 0x186a0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x186a0 pc=0x560fdd]

goroutine 65484531 [running]:
runtime.throw(0x11ac531, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0723f3de8 sp=0xc0723f3db8 pc=0x4a14b2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:727 +0x405 fp=0xc0723f3e18 sp=0xc0723f3de8 pc=0x4b7a05
github.com/dchest/siphash.Hash(0xdda7806a4847ec61, 0xb5940c2623a5aabd, 0x186a0, 0x8c7daf5b52fa, 0x8c7daf5b52fa, 0xc0723f3ee8)
	/app_data/price_feed_websocket/src/github.com/dchest/siphash/hash_amd64.s:27 +0x5d fp=0xc0723f3e20 sp=0xc0723f3e18 pc=0x560fdd
hashmap.getStringHash(0x186a0, 0x8c7daf5b52fa, 0x8)

**Comment by hello-100** [comment]
您好，您邮件已收，尽快给您回复。

**Comment by cornelk** [comment]
This looks like a crash in siphash, the library has been switched to use xxhash. Please create a new ticket and provide a test case if the problem still exists.
