### ISSUE TITLE
Question: is possible the values in `left` and `right` are change when inserting a new element?

### ISSUE THREAD

**Issue by drmingdrmer** [cornelk/hashmap#56]
When inserting a new element into the double-linked sorted list,
is there a chance that just before line 139, the node `left` and node `right` are replaced by another thread, but the address of `left` and `right` are still the same as before being replaced?

If possible, the list looks the same but node `left` and node `right` may already have different values.

Because the following CAS operations are based on pointer addresses, they can succeed.
But the `element` may be placed in an incorrect place since the values in `left` and `right` are already changed.

Is such a case prevented somewhere else if I missed something?

https://github.com/cornelk/hashmap/blob/c93d96ce6b8aa530423b5e10d4a56194284b47f6/list.go#L136-L148

**Comment by cornelk** [comment]
Thanks for your bug report, indeed the old implementation had some issues, the current dev branch has a singly linked list which should not have those issues anymore. Please review and create a new ticket if you see any other issue, thanks!

**Comment by drmingdrmer** [comment]
There is only a `bug_grow_insert` branch. Is it the **dev** branch you mentioned above?

**Comment by drmingdrmer** [comment]
Since `main` branch is still the default branch, closing this issue without fixing it is inappropriate for users.

Please keep an issue of an unsolved problem open, to let users know there is a risk in using this lib.

**Comment by cornelk** [comment]
Main is the default/dev branch, tags are releases. Since the code now uses a singly linked list, this issue is not present or valid anymore and gets closed.

**Comment by drmingdrmer** [comment]
I'm afraid the problem is still there as long as it uses a pointer address to identify an **unchanged** node:

The `right` has a chance it has been changed, but the address is the same.

Please keep this issue open until it's been fixed.

```go
func (l *List[Key, Value]) insertAt(element, left, right *ListElement[Key, Value]) bool {
	if left == nil {
		left = l.head
	}

	element.next.Store(right)

	if !left.next.CompareAndSwap(right, element) {
		return false // item was modified concurrently
	}

	l.count.Add(1)
	return true
}
```

**Comment by cornelk** [comment]
Thanks for reviewing it again. I will reopen the issue once I can clearly see/understand the problem.

The only issue I can see here is that if the function `insertAt` returns false due to a concurrent change of the next pointer of the left node, the inserting should be retried but currently the callers do not do that. Is this what you are referring to?

Other than that I can see no issue of using a pointer to identify a node. If there is still a reference/pointer to the node object, the GC should not garbage collect the object and reuse it.

**Comment by drmingdrmer** [comment]
You are right: `right` won't be GC-ed. I was wrong about it.

As you mentioned, the issue is that `left` or `right` has a chance it is already removed from the list when this method is called.
