### ISSUE TITLE
minor version updates break the API

### ISSUE THREAD

**Issue by tredeske** [cornelk/hashmap#66]
We updated our deps today, and discovered the new updates to hashmap have API changes even though the version changes are minor.  We're excited with the new changes, but we now have unexpected work to do.

Consider following this guidance: https://go.dev/doc/modules/release-workflow

We were using version 1.0.1, but all minor/patch versions past that are incompatible.

**Comment by cornelk** [comment]
Thanks for the feedback, I will use a new major version for breaking API changes.

Only the latest version contains fixes for all reported bugs, so there is no way for users to avoid using the latest version to get them.
