### ISSUE TITLE
Hang when using GetOrInsert and DEL

### ISSUE THREAD

**Issue by CMGS** [cornelk/hashmap#67]
**Describe the bug**
Hang when using GetOrInsert and DEL

**To Reproduce**
```
func TestDebug(t *testing.T) {
    m := hashmap.New[string, int]()

    var wg sync.WaitGroup
    key := "key"

    wg.Add(1)
    go func() {
        defer wg.Done()
        m.GetOrInsert(key, 9)
        m.Del(key)
    }()

    wg.Add(1)
    go func() {
        defer wg.Done()
        m.GetOrInsert(key, 9)
        m.Del(key)
    }()

    wg.Wait()
}
```

**Expected behavior**
not hang

**System (please complete the following information):**
 - OS: macos
 - Version / Commit: latest

**Comment by sunvim** [comment]
have been fixed in new pr, please see it

**Comment by CMGS** [comment]
lools working

**Comment by cornelk** [comment]
thanks for the bug report, a fix has been pushed to main
