### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by pyxiscloud** [cornelk/hashmap#72]
**Describe the bug**
After upgrade Go to 1.19.4 always got error on build

# github.com/cornelk/hashmap
../../GOLANG/pkg/mod/github.com/cornelk/hashmap@v1.0.8/list_element.go:17:13: invalid recursive type atomic.Pointer
  ../../GOLANG/pkg/mod/github.com/cornelk/hashmap@v1.0.8/list_element.go:17:13: atomic.Pointer refers to
  ../../GOLANG/pkg/mod/github.com/cornelk/hashmap@v1.0.8/list_element.go:17:22: ListElement refers to
  ../../GOLANG/pkg/mod/github.com/cornelk/hashmap@v1.0.8/list_element.go:17:13: atomic.Pointer

**To Reproduce**
install go 1.19.4
use hash map

**Expected behavior**
compile without errors

**System (please complete the following information):**
 - Mac OS 13.0.1:
 - hash map 1.0.8:

**Additional context**

**Comment by cornelk** [comment]
thanks for the report but it's a duplicate of https://github.com/cornelk/hashmap/issues/71

**Comment by cornelk** [comment]
this has been fixed with Go 1.19.5
