### ISSUE TITLE
Is it safe to call Del or Set during iterating via Range?

### ISSUE THREAD

**Issue by spacewander** [cornelk/hashmap#80]
When iterating the header via
https://github.com/cornelk/hashmap/blob/28d6fb92c67132d1bf08a5e07c81fdc5855bb460/hashmap.go#L224
will call Del or Set in the given `f` cause skipping of the header or repeat header access?

**Comment by MeteorsLiu** [comment]
It's safe, because the list is atomical. It depends who can swap the pointer first. There's only one thread can read/change the next element of the header, reading and changing  will not happen in the same time.

**Comment by spacewander** [comment]
@MeteorsLiu 
Thanks!
